_wandb:
    value:
        cli_version: 0.26.1
        e:
            eminyzjssdk0mqv1f8sk30yjqg2ty6ur:
                args:
                    - --data
                    - HI-Small
                    - --pretrain-epochs
                    - "5"
                    - --batch-size
                    - "512"
                codePath: Multi-GNN/pretrain_finetune.py
                codePathLocal: pretrain_finetune.py
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "120942624768"
                        used: "53767581696"
                email: zenithjoshua.27it@licet.ac.in
                executable: /usr/bin/python3
                git:
                    commit: 5f0d090a518111a098d130e5d147466ab2ca9572
                    remote: https://github.com/Jos-zenith/nolambur_case.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-d7ffa81e-8ee6-d1f6-6493-b4164d2d063b
                host: 035ff4658a7d
                memory:
                    total: "13605830656"
                os: Linux-6.6.122+-x86_64-with-glibc2.35
                program: /content/nolambur_case/Multi-GNN/pretrain_finetune.py
                python: CPython 3.12.13
                root: /content/nolambur_case/Multi-GNN
                startedAt: "2026-05-15T13:04:01.505435Z"
                writerId: eminyzjssdk0mqv1f8sk30yjqg2ty6ur
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 77
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 77
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.13
            "5": 0.26.1
            "6": 5.0.0
            "12": 0.26.1
            "13": linux-x86_64
finetune_dataset:
    value: nolambur
model:
    value: gin
pretrain_dataset:
    value: ibm_aml
