"""Tool schemas + dispatch for the manual agentic loop.

Schemas are hand-written (rather than generated by `@beta_tool`) so the loop in
orchestrator.py has no beta-SDK dependency and can also replay the transcript
into a final structured-output call.
"""

from __future__ import annotations

import json
from typing import Any

from . import bridge_client, tools_impl

TOOL_SCHEMAS: list[dict[str, Any]] = [
    {
        "name": "score_transaction",
        "description": (
            "DETECTOR. Score one UPI transfer with the T-GNN via the inference bridge. "
            "Returns a fraud probability, whether it was scored against the real background "
            "graph, and a model caveat. Real model, real dataset."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "sender_vpa": {"type": "string", "description": "Sender VPA or dataset account id."},
                "receiver_vpa": {"type": "string", "description": "Receiver VPA or dataset account id."},
                "amount_inr": {"type": "number"},
                "timestamp": {
                    "type": "string",
                    "description": "ISO 8601. Omit to use the dataset's latest timestamp.",
                },
            },
            "required": ["sender_vpa", "receiver_vpa", "amount_inr"],
        },
    },
    {
        "name": "score_transfer_chain",
        "description": (
            "DETECTOR. Score a suspected layering chain (multiple hops) in one call so the "
            "model sees the whole sub-graph. Use after list_downstream_transfers."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "legs": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "sender": {"type": "string"},
                            "receiver": {"type": "string"},
                            "amount_inr": {"type": "number"},
                            "timestamp": {"type": "string"},
                        },
                        "required": ["sender", "receiver", "amount_inr"],
                    },
                }
            },
            "required": ["legs"],
        },
    },
    {
        "name": "get_account_profile",
        "description": (
            "INVESTIGATOR. Behavioural summary of an account from the Nolambur dataset: "
            "in/out counts and amounts, distinct counterparties, first-in-to-first-out "
            "turnaround, transfers near 5L, counterparty states, and the dataset label."
        ),
        "input_schema": {
            "type": "object",
            "properties": {"vpa": {"type": "string"}},
            "required": ["vpa"],
        },
    },
    {
        "name": "list_downstream_transfers",
        "description": "INVESTIGATOR. Outgoing transfers from an account (earliest first) - trace the next hop.",
        "input_schema": {
            "type": "object",
            "properties": {
                "vpa": {"type": "string"},
                "limit": {"type": "integer", "description": "Default 20, max 100."},
            },
            "required": ["vpa"],
        },
    },
    {
        "name": "check_suspect_registry",
        "description": (
            "INVESTIGATOR. NPCI suspect-registry lookup over HTTP (the mock registry unless NPCI_REGISTRY_URL is set). "
            "Returns whether the VPA is listed and a mock record."
        ),
        "input_schema": {
            "type": "object",
            "properties": {"vpa": {"type": "string"}},
            "required": ["vpa"],
        },
    },
    {
        "name": "watch_downstream_stream",
        "description": (
            "MONITOR. Read the bridge's /stream replay for a few seconds and return the "
            "events, optionally filtered by a state name or label substring."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "seconds": {"type": "integer", "description": "2-15, default 6."},
                "filter_state": {"type": "string"},
            },
            "required": [],
        },
    },
    {
        "name": "freeze_account",
        "description": (
            "COORDINATOR. Account freeze: queues an HMAC-signed freeze instruction to the "
            "bank gateway webhook (the sandbox gateway unless GATEWAY_WEBHOOK_URL is set). "
            "Only call when a high score is corroborated by an independent signal."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "vpa": {"type": "string"},
                "reason": {"type": "string"},
            },
            "required": ["vpa", "reason"],
        },
    },
    {
        "name": "file_1930_report",
        "description": (
            "COORDINATOR. CFCFRMS / 1930 complaint: POSTs to the portal (the mock portal "
            "unless CFCFRMS_URL is set) and returns its acknowledgement number."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "vpas": {"type": "array", "items": {"type": "string"}},
                "case_summary": {"type": "string"},
                "total_amount_inr": {"type": "number"},
            },
            "required": ["vpas", "case_summary", "total_amount_inr"],
        },
    },
    {
        "name": "notify_officer",
        "description": (
            "COORDINATOR / MONITOR. Send an SMS alert to the on-call cyber-cell officer(s) via "
            "Twilio. Sends for real when TWILIO_* env vars are set, otherwise runs dry (logged "
            "to action_log.jsonl). Use after a freeze, a 1930 filing, or when starting to watch "
            "a corridor."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "description": "Concise: accounts, amount, corridor, action taken.",
                },
                "priority": {"type": "string", "enum": ["low", "medium", "high", "critical"]},
            },
            "required": ["message"],
        },
    },
]

_DISPATCH = {
    "score_transaction": tools_impl.score_transaction,
    "score_transfer_chain": tools_impl.score_transfer_chain,
    "get_account_profile": tools_impl.get_account_profile,
    "list_downstream_transfers": tools_impl.list_downstream_transfers,
    "check_suspect_registry": tools_impl.check_suspect_registry,
    "watch_downstream_stream": tools_impl.watch_downstream_stream,
    "freeze_account": tools_impl.freeze_account,
    "file_1930_report": tools_impl.file_1930_report,
    "notify_officer": tools_impl.notify_officer,
}


def run_tool(name: str, tool_input: dict[str, Any]) -> tuple[str, bool]:
    """Execute a tool. Returns (json_string, is_error)."""
    function = _DISPATCH.get(name)
    if function is None:
        return json.dumps({"error": f"unknown tool: {name}"}), True
    try:
        return json.dumps(function(**tool_input), default=str), False
    except bridge_client.BridgeUnavailable as error:
        return json.dumps({"error": "bridge_unavailable", "detail": str(error)}), True
    except TypeError as error:
        return json.dumps({"error": "bad_arguments", "detail": str(error)}), True
    except Exception as error:  # noqa: BLE001 - surface any tool failure to the model
        return json.dumps({"error": type(error).__name__, "detail": str(error)}), True
