_wandb:
    value:
        cli_version: 0.26.1
        e:
            avfza6i0xhdiwq1p8q86jgsi8z1r4c7s:
                args:
                    - --model
                    - gin
                    - --data
                    - HI-Small
                    - --batch-size
                    - "256"
                    - --seed
                    - "42"
                    - --epochs
                    - "100"
                    - --save-model
                    - --save-dir
                    - models
                codePath: pretrain_finetune.py
                codePathLocal: pretrain_finetune.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "511423016960"
                        used: "130158641152"
                email: zenithjoshua.27it@licet.ac.in
                executable: C:\Users\Zenith Joshua\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: 252b0252afca109d1d216c411c59ff70753b25fc
                    remote: https://github.com/IBM/Multi-GNN.git
                host: DESKTOP-TV1J24N
                memory:
                    total: "16908926976"
                os: Windows-11-10.0.26200-SP0
                program: D:\betty\cyber\fraud-detection-system\Multi-GNN\pretrain_finetune.py
                python: CPython 3.12.10
                root: D:\betty\cyber\fraud-detection-system\Multi-GNN
                startedAt: "2026-05-14T19:07:32.592974Z"
                writerId: avfza6i0xhdiwq1p8q86jgsi8z1r4c7s
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 77
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 77
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.10
            "5": 0.26.1
            "6": 4.57.3
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
finetune_dataset:
    value: nolambur
model:
    value: gin
pretrain_dataset:
    value: ibm_aml
